/*
 * File: app/view/BrowsePanelViewModel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Domino.view.BrowsePanelViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.browsepanel',

    requires: [
        'Ext.data.Store',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json',
        'Ext.data.field.Field'
    ],

    stores: {
        SubjectsListStore: {
            autoLoad: true,
            model: 'Domino.model.SubjectModel',
            proxy: {
                type: 'ajax',
                url: 'data/SoggettiLista.json',
                reader: {
                    type: 'json',
                    rootProperty: 'subjects'
                }
            }
        },
        MenuStore: {
            proxy: {
                type: 'ajax',
                url: 'data/Menu.json',
                reader: {
                    type: 'json',
                    rootProperty: 'items'
                }
            },
            fields: [
                {
                    name: 'name'
                },
                {
                    name: 'url'
                },
                {
                    name: 'id'
                }
            ]
        },
        subjectDetailStore: {
            autoLoad: true,
            model: 'Domino.model.SubjectModel',
            proxy: {
                type: 'ajax',
                url: 'data/Soggetto1.json',
                reader: {
                    type: 'json',
                    rootProperty: 'subject'
                }
            }
        }
    }

});