/*
 * File: app/view/BrowsePanelViewController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Domino.view.BrowsePanelViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.browsepanel',

    onBrowseDetailSelect: function(rowmodel, record, index, eOpts) {
        var me = this;
        // è necessario passare un oggetto arbitrario rec (o altro nome) per poterlo puntare dal binding
        me.view.down("#leftDetailPanel").up('#browsePanel').getViewModel().setData({rec:record});


    },

    onMenuitemClick: function(item, e, eOpts) {


        var i = item.up("#browsePanel");
        var store = i.viewModel.storeInfo.SubjectsListStore;
        var proxy = store.proxy;
        proxy.url  ="data/SoggettiMaschi.json";
        store.load();
    },

    onMenuitemClick1: function(item, e, eOpts) {
        var i = item.up("#browsePanel");
        var store = i.viewModel.storeInfo.SubjectsListStore;
        var proxy = store.proxy;
        proxy.url  ="data/SoggettiFemmine.json";
        store.load();
    }

});
