/*
 * File: app/view/DashPanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Domino.view.DashPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.dashpanel',

    requires: [
        'Domino.view.DashPanelViewModel',
        'Ext.panel.Panel',
        'Ext.form.Label'
    ],

    viewModel: {
        type: 'dashpanel'
    },
    id: 'dashPanel',
    itemId: 'dashPanel',
    layout: 'absolute',
    bodyStyle: 'background:#D1ECF9;',
    header: false,
    title: 'Dashboard',

    items: [
        {
            xtype: 'panel',
            x: 20,
            y: 20,
            height: 140,
            id: 'helpPanel',
            itemId: 'helpPanel',
            width: 240,
            bodyStyle: 'background:#75D175;',
            header: false,
            title: 'My Panel',
            items: [
                {
                    xtype: 'label',
                    baseCls: 'x-component textNormal',
                    text: 'Presentazione, guida e novità'
                }
            ]
        }
    ]

});