/*
 * File: app/view/HomePage.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Domino.view.HomePage', {
    extend: 'Ext.container.Container',
    alias: 'widget.homepage',

    requires: [
        'Domino.view.HomePageViewModel',
        'Domino.view.HomePageViewController',
        'Domino.view.MenuPanel',
        'Domino.view.ContentPanel',
        'Ext.panel.Panel',
        'Ext.form.Label',
        'Ext.button.Button'
    ],

    controller: 'homepage',
    viewModel: {
        type: 'homepage'
    },
    id: 'homePage',
    itemId: 'homePage',
    layout: 'border',

    items: [
        {
            xtype: 'panel',
            region: 'north',
            height: 80,
            id: 'headerPanel',
            itemId: 'headerPanel',
            bodyStyle: 'background:#1BA1E2;',
            header: false,
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'container',
                    flex: 3,
                    id: 'titleContainer',
                    itemId: 'titleContainer',
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'label',
                            margin: '20% 20 20% 20',
                            text: 'DOMINO'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 1,
                    id: 'userContainer',
                    itemId: 'userContainer',
                    padding: '20 0 0 0 ',
                    width: '100%',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            style: 'text-align:center;',
                            width: 150,
                            items: [
                                {
                                    xtype: 'label',
                                    height: 150,
                                    id: 'userNameSpan',
                                    itemId: 'userNameSpan',
                                    text: 'Michele Rubin'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            style: 'text-align:center;',
                            items: [
                                {
                                    xtype: 'button',
                                    id: 'logoutCmd',
                                    itemId: 'logoutCmd',
                                    margin: '0 0 0 10',
                                    maxWidth: 100,
                                    width: 150,
                                    text: 'Logout',
                                    listeners: {
                                        click: 'onLogoutCmdClick'
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'menupanel',
            region: 'west'
        },
        {
            xtype: 'contentpanel',
            region: 'center'
        }
    ]

});