/*
 * File: app/view/HomeContainer.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Domino.view.HomeContainer', {
    extend: 'Ext.container.Container',
    alias: 'widget.homecontainer',

    requires: [
        'Domino.view.HomeContainerViewModel',
        'Domino.view.HomeContainerViewController',
        'Ext.form.Label',
        'Ext.button.Button',
        'Ext.menu.Menu',
        'Ext.menu.Separator'
    ],

    controller: 'homecontainer',
    viewModel: {
        type: 'homecontainer'
    },
    height: '100%',
    id: 'homeContainer',
    itemId: 'homeContainer',
    width: '100%',
    layout: 'border',

    items: [
        {
            xtype: 'panel',
            region: 'north',
            height: 80,
            id: 'headerPanel',
            itemId: 'headerPanel',
            bodyStyle: 'background:#1BA1E2;',
            header: false,
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'container',
                    flex: 3,
                    id: 'titleContainer',
                    itemId: 'titleContainer',
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'label',
                            margin: '20% 20 20% 20',
                            text: 'DOMINO'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 1,
                    id: 'userContainer',
                    itemId: 'userContainer',
                    items: [
                        {
                            xtype: 'label',
                            id: 'userNameSpan',
                            itemId: 'userNameSpan',
                            text: 'Michele Rubin'
                        },
                        {
                            xtype: 'button',
                            id: 'logoutCmd',
                            itemId: 'logoutCmd',
                            text: 'Logout',
                            listeners: {
                                click: 'onLogoutCmdClick'
                            }
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            region: 'west',
            width: 150,
            bodyStyle: 'background:#75C6EE;',
            header: false,
            title: 'menuPanel',
            dockedItems: [
                {
                    xtype: 'menu',
                    dock: 'bottom',
                    floating: false,
                    id: 'mainMenu',
                    itemId: 'mainMenu',
                    width: 120,
                    items: [
                        {
                            xtype: 'menuitem',
                            id: 'homeMenuItem',
                            style: 'background:#1BA1E2;',
                            text: 'Home page'
                        },
                        {
                            xtype: 'menuseparator',
                            id: 'topSeparator'
                        },
                        {
                            xtype: 'menuitem',
                            id: 'notificationsMenuItem',
                            style: 'background:#1BA1E2;',
                            text: 'Notifiche'
                        },
                        {
                            xtype: 'menuseparator',
                            id: 'middleSeparator'
                        },
                        {
                            xtype: 'menuitem',
                            id: 'browseMenuItem',
                            style: 'background:#1BA1E2;',
                            text: 'Sfoglia'
                        },
                        {
                            xtype: 'menuseparator',
                            id: 'bottomSeparator'
                        },
                        {
                            xtype: 'menuitem',
                            id: 'settingsMenuItem',
                            style: 'background:#1BA1E2;',
                            text: 'Acquista e configura'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            region: 'center',
            header: false,
            title: 'contentPanel'
        }
    ]

});