/*
 * File: app/view/LoginMenu.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Domino.view.LoginMenu', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.loginmenu',

    requires: [
        'Domino.view.LoginMenuViewModel',
        'Domino.view.LoginMenuViewController',
        'Ext.menu.Menu',
        'Ext.menu.Item'
    ],

    controller: 'loginmenu',
    viewModel: {
        type: 'loginmenu'
    },
    margin: '200 0 200 0',
    minWidth: 300,
    width: 150,
    bodyPadding: 10,
    header: false,
    title: 'Login Menu',

    items: [
        {
            xtype: 'menu',
            floating: false,
            width: '100%',
            items: [
                {
                    xtype: 'menuitem',
                    text: 'Login',
                    listeners: {
                        click: 'onMenuitemClick'
                    }
                },
                {
                    xtype: 'menuitem',
                    text: 'Login Facebook'
                },
                {
                    xtype: 'menuitem',
                    text: 'Login Google'
                }
            ]
        }
    ]

});