/*
 * File: app/view/LoginPanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Domino.view.LoginPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.loginpanel',

    requires: [
        'Domino.view.LoginPanelViewModel',
        'Domino.view.LoginPanelViewController',
        'Ext.menu.Menu',
        'Ext.menu.Item',
        'Ext.XTemplate'
    ],

    controller: 'loginpanel',
    viewModel: {
        type: 'loginpanel'
    },
    margin: '200 0 200 0',
    width: '',
    bodyPadding: 10,
    header: false,
    title: 'Login Menu',

    items: [
        {
            xtype: 'menu',
            floating: false,
            id: 'loginMenu',
            itemId: 'loginMenu',
            tpl: [
                'Link:<a>{title}<a>'
            ],
            width: '100%',
            items: [
                {
                    xtype: 'menuitem',
                    text: 'Login',
                    listeners: {
                        click: 'onMenuitemClick'
                    }
                },
                {
                    xtype: 'menuitem',
                    text: 'Login via Twitter'
                },
                {
                    xtype: 'menuitem',
                    text: 'Login via Google'
                }
            ],
            listeners: {
                activate: 'onMenuActivate'
            }
        }
    ]

});