/*
 * File: app/view/MainContainer.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Domino.view.MainContainer', {
    extend: 'Ext.container.Container',
    alias: 'widget.mainContainer',

    requires: [
        'Domino.view.MainContainerViewModel',
        'Ext.panel.Panel'
    ],

    viewModel: {
        type: 'maincontainer'
    },
    height: '100%',
    id: 'mainViewport',
    itemId: 'mainContainer',
    width: '100%',

    items: [
        {
            xtype: 'panel',
            height: '100%',
            manageHeight: false,
            title: 'My Panel'
        }
    ]

});