/*
 * File: app/view/MenuPanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Domino.view.MenuPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.menupanel',

    requires: [
        'Domino.view.MenuPanelViewModel',
        'Domino.view.MenuPanelViewController',
        'Ext.menu.Menu',
        'Ext.menu.Separator'
    ],

    controller: 'menupanel',
    viewModel: {
        type: 'menupanel'
    },
    baseCls: 'x-panel menuPanel',
    id: 'menuPanel',
    itemId: 'menuPanel',
    width: 150,
    header: false,
    title: 'menuPanel',

    dockedItems: [
        {
            xtype: 'menu',
            dock: 'bottom',
            floating: false,
            id: 'mainMenu',
            itemId: 'mainMenu',
            width: 120,
            items: [
                {
                    xtype: 'menuitem',
                    baseCls: 'x-menu-item mainMenuItem',
                    id: 'dashMenuItem',
                    text: 'Dashboard',
                    listeners: {
                        click: 'onDashMenuItemClick'
                    }
                },
                {
                    xtype: 'menuseparator',
                    hidden: true,
                    id: 'topSeparator'
                },
                {
                    xtype: 'menuitem',
                    baseCls: 'x-menu-item mainMenuItem',
                    id: 'notificationsMenuItem',
                    text: 'Notifiche'
                },
                {
                    xtype: 'menuseparator',
                    hidden: true,
                    id: 'middleSeparator'
                },
                {
                    xtype: 'menuitem',
                    baseCls: 'x-menu-item mainMenuItem',
                    id: 'browseMenuItem',
                    text: 'Sfoglia',
                    listeners: {
                        click: 'onBrowseMenuItemClick'
                    }
                },
                {
                    xtype: 'menuseparator',
                    hidden: true,
                    id: 'bottomSeparator'
                },
                {
                    xtype: 'menuitem',
                    baseCls: 'x-menu-item mainMenuItem',
                    id: 'settingsMenuItem',
                    text: 'Acquista e configura'
                }
            ]
        }
    ]

});