/*
 * File: app/view/MyViewport1.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Domino.view.MyViewport1', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.myviewport1',

    requires: [
        'Domino.view.MyViewport1ViewModel',
        'Ext.panel.Panel',
        'Ext.XTemplate'
    ],

    viewModel: {
        type: 'myviewport1'
    },

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'container',
            flex: 1,
            height: '100%',
            width: '100%',
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'panel',
                    flex: 3,
                    baseCls: 'x-panel promotionPanel',
                    cls: '',
                    width: '100%',
                    title: 'PromotionPanel',
                    items: [
                        {
                            xtype: 'container',
                            height: '40%',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            }
                        },
                        {
                            xtype: 'container',
                            height: '40%',
                            layout: {
                                type: 'vbox',
                                align: 'stretch',
                                pack: 'end'
                            },
                            items: [
                                {
                                    xtype: 'panel',
                                    flex: 1,
                                    tpl: [
                                        'Area promozionale'
                                    ],
                                    title: 'Area Promozionale',
                                    titleAlign: 'center'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            layout: {
                                type: 'vbox',
                                align: 'stretch',
                                pack: 'center'
                            }
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    flex: 2,
                    maxWidth: 300,
                    minWidth: 300,
                    width: '',
                    title: 'Login'
                }
            ]
        }
    ]

});