/*
 * File: app/store/ProfitLoss.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Dashboard.store.ProfitLoss', {
    extend: 'Ext.data.Store',
    alias: 'store.profitloss',

    requires: [
        'Dashboard.model.FullProfitLoss',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'ProfitLoss',
            autoLoad: true,
            model: 'Dashboard.model.FullProfitLoss',
            proxy: {
                type: 'ajax',
                url: 'resources/data/full_data.json',
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    }
});