/*
 * File: app/controller/MyController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MVVM.controller.MyController', {
    extend: 'Ext.app.Controller',
    alias: 'controller.Master',

    init: function(application) {
        this.control({
                     'MasterView': {
                         select : this.onGridSelect
                     }
                 });
    },

    onGridSelect: function(grid, record, index, eOpts) {
        // grab a reference to the Detail view...
                // we could have used a controller "ref", but those can also be problematic
                var detailView = Ext.ComponentQuery.query('DetailView')[0];

                //set the form's ViewModel binding
                detailView.getViewModel().setData({ rec: record });
    }

});
