/*
 * File: app/view/profitloss/ProfitLoss.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Dashboard.view.profitloss.ProfitLoss', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.profitloss',

    requires: [
        'Dashboard.view.profitloss.ProfitLossViewModel',
        'Dashboard.view.profitloss.ProfitLossViewController',
        'Ext.grid.column.Column',
        'Ext.grid.View',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.menu.Menu'
    ],

    controller: 'profitloss',
    viewModel: {
        type: 'profitloss.ProfitLossViewModel'
    },
    title: 'Profit and Loss',
    store: 'ProfitLoss',

    columns: [
        {
            xtype: 'gridcolumn',
            dataIndex: 'region',
            text: 'Region'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'account',
            text: 'Account'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'q1_2010',
            text: 'Q1_2010'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'q2_2010',
            text: 'Q2_2010'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'q3_2010',
            text: 'Q3_2010'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'q4_2010',
            text: 'Q4_2010'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'q1_2011',
            text: 'Q1_2011'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'q2_2011',
            text: 'Q2_2011'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'q3_2011',
            text: 'Q3_2011'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'q4_2011',
            text: 'Q4_2011'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'q1_2012',
            text: 'Q1_2012'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'q2_2012',
            text: 'Q2_2012'
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'button',
                    reference: 'regionsButton',
                    width: 150,
                    text: 'Region',
                    textAlign: 'left',
                    menu: {
                        xtype: 'menu',
                        id: 'region-menu',
                        width: 200
                    }
                }
            ]
        }
    ]

});