/*
 * File: app/view/Detail.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MVVM.view.Detail', {
    extend: 'Ext.form.Panel',
    alias: 'widget.DetailView',

    requires: [
        'MVVM.view.DetailViewModel',
        'Ext.form.field.Text',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'detailform'
    },
    frame: true,
    padding: 10,
    title: 'Detail Panel',

    items: [
        {
            xtype: 'textfield',
            bind: '{rec.name}',
            anchor: '100%',
            fieldLabel: 'Name'
        },
        {
            xtype: 'textfield',
            bind: '{rec.email}',
            anchor: '100%',
            fieldLabel: 'Email'
        },
        {
            xtype: 'textfield',
            bind: '{rec.phone}',
            anchor: '100%',
            fieldLabel: 'Phone'
        },
        {
            xtype: 'button',
            text: 'Save'
        }
    ]

});